insert into country (country.id,country.short,country.full_en,country.full_cn)
values
(1,"美","美国","The United States"),
(2,"日","日本","Japan"),
(3,"法","法国","The French"),
(4,"中","中国","China"),
(5,"哥","哥伦比亚","Colombia"),
(6,"清","清朝","The qing dynasty"),
(7,"捷","捷克","The Czech republic"),
(8,"英","英国","The British"),
(10,"以","以色列","Israel"),
(11,"明","明朝","The Ming dynasty"),
(12,"巴","巴西","Brazil"),
(13,"挪","挪威","The Norwegian"),
(14,"奥","奥地利","Austria"),
(15,"丹","丹麦","The Danish"),
(16,"德","德国","Germany"),
(18,"澳","澳大利亚","Australia"),
(19,"印","印度","India"),
(17,"意","意大利","Italy"),
(9,"瑞","瑞典","The Swedish");